networks:
  backend: 
  frontend:

services:
  # Staff Database 
  uttambsolutionsstaffdb:
     container_name: uttamb_solutions_limited_database
     image: mcr.microsoft.com/mssql/server:2022-latest
     environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Password123!
     ports:
        - "18001:1433"
     networks:
        - backend

  # Staff Microservice
  uttambsolutionsstaff:
    container_name: uttamb_solutions_limited_staffs
    image: ${DOCKER_REGISTRY-}uttambsolutionsstaff
    build:
      context: .
      dockerfile: Uttambsolutionsstaff/Dockerfile
    networks:
       - backend
    environment:
      - DB_HOST=uttamb_solutions_limited_staff_server
      - DB_NAME=Uttambsolutionsstaffdb
      - DB_USERNAME=sa
      - DB_SA_PASSWORD=Password123!

  # Customer Microservice
  uttambsolutionscustomer:
    container_name: uttamb_solutions_limited_customers
    image: ${DOCKER_REGISTRY-}uttambsolutionscustomer
    build:
      context: .
      dockerfile: Uttambsolutionscustomer/Dockerfile
    networks:
       - backend
       

  # API Gateway
  apigateway:
    container_name: uttamb_solutions_api_gateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateWay/Dockerfile
    ports:
      - 8002:8080
    networks:
       - backend
       - frontend
